### PR TITLE
Improve Etude manager

### LINKED ISSUE #45: supprimer la référence statique au premier mandat de Mgate.
Anciennement @ [src/mgate/SuiviBundle/Manager/EtudeManager.php, line 242](https://github.com/N7-Consulting/Incipio/blob/45fb18b12729502f2d9f992d678fbaaa543d4e66/src/mgate/SuiviBundle/Manager/EtudeManager.php#L242)

$mandat = 2007 + getMaxMandat()

Ce problème se résout facilement. Il y a déjà la date de création dans le parameters.yml : anneeCreation. Il suffit de l'importer et l'utiliser

### PR DESCRIPTION
**Pull request by Stoakes**
* Remove unused methods
* Use anneCreation parameter instead of hard-coded 2007 value (Fix #45)
* Fix typo in anneeCreation parameter

Execute the following migration to update your database parameter table
```
docker-compose exec web php bin/console doctrine:migrations:execute 20170614232630
```

### CODE REVIEW

**Comment by Olivier-R** [comment]
Seems alright :+1:

**Comment by theofidry** [comment]
When merging you should rather do a `Squash & merge`, it helps to keep a cleaner git history

**Comment by Stoakes** [comment]
Sure.

For this PR it's what I was supposed to do. And it [seems to be ok](https://github.com/n7consulting/Incipio/commits/dev) isn't it ?

**Comment by theofidry** [comment]
Hm indeed, though I saw something else but I may have been confused by the `merged X commits to dev`

**Pull request merged**
