### PR TITLE
Update ubuntu installation script to use docker latest & work on Ubun…

### PR DESCRIPTION
**Pull request by Stoakes**
…tu 18.04

Tested on Digital Oceans droplets using Ubuntu 18.04 & 16.04.

Other tests welcomed.

### CODE REVIEW

**Comment by PitouGames** [comment]
Tested on a Oracle VM Virtualbox with a new Ubuntu18.04 install.
It can't install "docker-ce". The installation is a fail but writes that's OK at the end. Not easy to understand for a beginner.
<details> 
  <summary>Output : </summary>

ubuntu1804@ubuntu1804-VirtualBox:/var/www/Incipio$ sudo ./var/install/initial-setup_ubuntu16.sh

Hit:1 http://fr.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:3 http://fr.archive.ubuntu.com/ubuntu bionic-updates InRelease                          
Hit:4 http://fr.archive.ubuntu.com/ubuntu bionic-backports InRelease                                
Get:5 https://download.docker.com/linux/ubuntu bionic InRelease [64,4 kB]                           
Err:5 https://download.docker.com/linux/ubuntu bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
Reading package lists... Done
W: GPG error: https://download.docker.com/linux/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
E: The repository 'https://download.docker.com/linux/ubuntu bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ca-certificates is already the newest version (20180409).
software-properties-common is already the newest version (0.96.24.32.3).
apt-transport-https is already the newest version (1.6.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
./var/install/initial-setup_ubuntu16.sh: line 8: curl: command not found
gpg: no valid OpenPGP data found.
Hit:1 http://fr.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease                                   
Hit:3 http://fr.archive.ubuntu.com/ubuntu bionic-updates InRelease                                  
Hit:4 http://fr.archive.ubuntu.com/ubuntu bionic-backports InRelease                                
Get:5 https://download.docker.com/linux/ubuntu bionic InRelease [64,4 kB]                           
ubuntu1804@ubuntu1804-VirtualBox:/var/www/Incipio$ sudo ./var/install/initial-setup_ubuntu16.sh 
Hit:1 http://fr.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease                                
Hit:3 http://fr.archive.ubuntu.com/ubuntu bionic-updates InRelease                                  
Hit:4 http://fr.archive.ubuntu.com/ubuntu bionic-backports InRelease                                
Get:5 https://download.docker.com/linux/ubuntu bionic InRelease [64,4 kB]                           
Err:5 https://download.docker.com/linux/ubuntu bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
Reading package lists... Done
W: GPG error: https://download.docker.com/linux/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
E: The repository 'https://download.docker.com/linux/ubuntu bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ca-certificates is already the newest version (20180409).
software-properties-common is already the newest version (0.96.24.32.3).
apt-transport-https is already the newest version (1.6.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
./var/install/initial-setup_ubuntu16.sh: line 8: curl: command not found
gpg: no valid OpenPGP data found.
Hit:1 http://fr.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease                                   
Hit:3 http://fr.archive.ubuntu.com/ubuntu bionic-updates InRelease                                  
Hit:4 http://fr.archive.ubuntu.com/ubuntu bionic-backports InRelease                                
Get:5 https://download.docker.com/linux/ubuntu bionic InRelease [64,4 kB]                           
Err:5 https://download.docker.com/linux/ubuntu bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
Reading package lists... Done
W: GPG error: https://download.docker.com/linux/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
E: The repository 'https://download.docker.com/linux/ubuntu bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Hit:1 http://fr.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease                                   
Hit:3 http://fr.archive.ubuntu.com/ubuntu bionic-updates InRelease                                  
Hit:4 http://fr.archive.ubuntu.com/ubuntu bionic-backports InRelease                                
Get:5 https://download.docker.com/linux/ubuntu bionic InRelease [64,4 kB]                           
Err:5 https://download.docker.com/linux/ubuntu bionic InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
Reading package lists... Done
W: GPG error: https://download.docker.com/linux/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
E: The repository 'https://download.docker.com/linux/ubuntu bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'docker-ce' has no installation candidate
./var/install/initial-setup_ubuntu16.sh: line 12: docker: command not found
./var/install/initial-setup_ubuntu16.sh: line 15: curl: command not found
chmod: cannot access '/usr/local/bin/docker-compose': No such file or directory
./var/install/initial-setup_ubuntu16.sh: line 17: docker-compose: command not found
What is the domain name that points on that server (crm.n7consulting.fr) :
crm.test.fr
What is your contact email adress (contact@n7consulting.fr) :
contact@pitou.fr
./var/install/initial-setup_ubuntu16.sh: line 35: docker-compose: command not found
./var/install/initial-setup_ubuntu16.sh: line 36: docker-compose: command not found
Waiting some seconds before setting up the database
./var/install/initial-setup_ubuntu16.sh: line 41: docker-compose: command not found
Installation is now complete. You can now log in with credentials admin/admin. Don't forget to change that password.
</details>

**Comment by Stoakes** [comment]
Thanks for the logs. Interesting.

FA7 Junior Etudes, used  successfully the script on their new Ubuntu 18 server, without any patch.

`./var/install/initial-setup_ubuntu16.sh: line 8: curl: command not found`

Your VM (and that is something we will have to patch in the script to prevent it from failing), doesn't have curl, which is used to retrieve docker and docker-compose, which brings the failure

**Comment by Stoakes** [comment]
Script updated, it should now work.

**Comment by PitouGames** [comment]
Yes, it works great on my VM !

**Pull request merged**
